language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO_VERSION="django>=1.11.17,<1.12"
  - DJANGO_VERSION="django>=2.0,<2.1"
  - DJANGO_VERSION="django>=2.1,<2.2"
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION="django>=2.0,<2.1"
    - python: "2.7"
      env: DJANGO_VERSION="django>=2.1,<2.2"
    - python: "3.4"
      env: DJANGO_VERSION="django>=2.1,<2.2"
install:
  - pip install -r requirements.txt
  - pip install $DJANGO_VERSION
  - python setup.py install
script: make test
